// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/discount.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Discount struct {
	PriceInCents         int64    `protobuf:"varint,1,opt,name=priceInCents,proto3" json:"priceInCents,omitempty"`
	Percentual           float32  `protobuf:"fixed32,2,opt,name=percentual,proto3" json:"percentual,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Discount) Reset()         { *m = Discount{} }
func (m *Discount) String() string { return proto.CompactTextString(m) }
func (*Discount) ProtoMessage()    {}
func (*Discount) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{0}
}

func (m *Discount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discount.Unmarshal(m, b)
}
func (m *Discount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discount.Marshal(b, m, deterministic)
}
func (m *Discount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discount.Merge(m, src)
}
func (m *Discount) XXX_Size() int {
	return xxx_messageInfo_Discount.Size(m)
}
func (m *Discount) XXX_DiscardUnknown() {
	xxx_messageInfo_Discount.DiscardUnknown(m)
}

var xxx_messageInfo_Discount proto.InternalMessageInfo

func (m *Discount) GetPriceInCents() int64 {
	if m != nil {
		return m.PriceInCents
	}
	return 0
}

func (m *Discount) GetPercentual() float32 {
	if m != nil {
		return m.Percentual
	}
	return 0
}

type GetDiscountRequest struct {
	ProductID            int64    `protobuf:"varint,1,opt,name=productID,proto3" json:"productID,omitempty"`
	UserID               int64    `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDiscountRequest) Reset()         { *m = GetDiscountRequest{} }
func (m *GetDiscountRequest) String() string { return proto.CompactTextString(m) }
func (*GetDiscountRequest) ProtoMessage()    {}
func (*GetDiscountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{1}
}

func (m *GetDiscountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDiscountRequest.Unmarshal(m, b)
}
func (m *GetDiscountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDiscountRequest.Marshal(b, m, deterministic)
}
func (m *GetDiscountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDiscountRequest.Merge(m, src)
}
func (m *GetDiscountRequest) XXX_Size() int {
	return xxx_messageInfo_GetDiscountRequest.Size(m)
}
func (m *GetDiscountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDiscountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDiscountRequest proto.InternalMessageInfo

func (m *GetDiscountRequest) GetProductID() int64 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *GetDiscountRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type GetDiscountResponse struct {
	Discount             *Discount `protobuf:"bytes,1,opt,name=discount,proto3" json:"discount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetDiscountResponse) Reset()         { *m = GetDiscountResponse{} }
func (m *GetDiscountResponse) String() string { return proto.CompactTextString(m) }
func (*GetDiscountResponse) ProtoMessage()    {}
func (*GetDiscountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{2}
}

func (m *GetDiscountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDiscountResponse.Unmarshal(m, b)
}
func (m *GetDiscountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDiscountResponse.Marshal(b, m, deterministic)
}
func (m *GetDiscountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDiscountResponse.Merge(m, src)
}
func (m *GetDiscountResponse) XXX_Size() int {
	return xxx_messageInfo_GetDiscountResponse.Size(m)
}
func (m *GetDiscountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDiscountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDiscountResponse proto.InternalMessageInfo

func (m *GetDiscountResponse) GetDiscount() *Discount {
	if m != nil {
		return m.Discount
	}
	return nil
}

func init() {
	proto.RegisterType((*Discount)(nil), "proto.Discount")
	proto.RegisterType((*GetDiscountRequest)(nil), "proto.GetDiscountRequest")
	proto.RegisterType((*GetDiscountResponse)(nil), "proto.GetDiscountResponse")
}

func init() { proto.RegisterFile("proto/discount.proto", fileDescriptor_d27f2fd5df31734b) }

var fileDescriptor_d27f2fd5df31734b = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xcd, 0x4a, 0xc5, 0x30,
	0x10, 0x85, 0xed, 0xbd, 0x78, 0xa9, 0x53, 0xa1, 0x30, 0x8a, 0xd4, 0x22, 0x52, 0xb2, 0x2a, 0x08,
	0x15, 0xea, 0x1b, 0x68, 0x51, 0xea, 0xc2, 0x45, 0x5c, 0xb9, 0xd4, 0x74, 0x16, 0x05, 0x49, 0x62,
	0x7e, 0x7c, 0x7e, 0x21, 0x4d, 0x6b, 0x8b, 0xae, 0xc2, 0x7c, 0x67, 0xf2, 0x31, 0x07, 0xce, 0xb5,
	0x51, 0x4e, 0xdd, 0x0e, 0xa3, 0x15, 0xca, 0x4b, 0xd7, 0x84, 0x11, 0x8f, 0xc3, 0xc3, 0x5e, 0x20,
	0xed, 0x62, 0x80, 0x0c, 0x4e, 0xb5, 0x19, 0x05, 0xf5, 0xf2, 0x81, 0xa4, 0xb3, 0x45, 0x52, 0x25,
	0xf5, 0x9e, 0x6f, 0x18, 0x5e, 0x03, 0x68, 0x32, 0x82, 0xa4, 0xf3, 0xef, 0x9f, 0xc5, 0xae, 0x4a,
	0xea, 0x1d, 0x5f, 0x11, 0xf6, 0x0c, 0xf8, 0x44, 0x6e, 0x56, 0x72, 0xfa, 0xf2, 0x64, 0x1d, 0x5e,
	0xc1, 0x89, 0x36, 0x6a, 0xf0, 0xc2, 0xf5, 0x5d, 0xd4, 0xfe, 0x02, 0xbc, 0x80, 0x83, 0xb7, 0x64,
	0xfa, 0x2e, 0xf8, 0xf6, 0x3c, 0x4e, 0xec, 0x1e, 0xce, 0x36, 0x2e, 0xab, 0x95, 0xb4, 0x84, 0x37,
	0x90, 0xce, 0x5d, 0x82, 0x2b, 0x6b, 0xf3, 0xa9, 0x53, 0xb3, 0xac, 0x2e, 0x0b, 0xed, 0x1b, 0xe4,
	0x33, 0x7d, 0x25, 0xf3, 0x3d, 0x0a, 0xc2, 0x47, 0xc8, 0x56, 0x5a, 0xbc, 0x8c, 0x9f, 0xff, 0x9e,
	0x5d, 0x96, 0xff, 0x45, 0xd3, 0x15, 0xec, 0xe8, 0xe3, 0x10, 0xc2, 0xbb, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x1d, 0xc6, 0xe1, 0xe2, 0x60, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiscountServiceClient is the client API for DiscountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscountServiceClient interface {
	GetDiscount(ctx context.Context, in *GetDiscountRequest, opts ...grpc.CallOption) (*GetDiscountResponse, error)
}

type discountServiceClient struct {
	cc *grpc.ClientConn
}

func NewDiscountServiceClient(cc *grpc.ClientConn) DiscountServiceClient {
	return &discountServiceClient{cc}
}

func (c *discountServiceClient) GetDiscount(ctx context.Context, in *GetDiscountRequest, opts ...grpc.CallOption) (*GetDiscountResponse, error) {
	out := new(GetDiscountResponse)
	err := c.cc.Invoke(ctx, "/proto.DiscountService/GetDiscount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscountServiceServer is the server API for DiscountService service.
type DiscountServiceServer interface {
	GetDiscount(context.Context, *GetDiscountRequest) (*GetDiscountResponse, error)
}

// UnimplementedDiscountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDiscountServiceServer struct {
}

func (*UnimplementedDiscountServiceServer) GetDiscount(ctx context.Context, req *GetDiscountRequest) (*GetDiscountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiscount not implemented")
}

func RegisterDiscountServiceServer(s *grpc.Server, srv DiscountServiceServer) {
	s.RegisterService(&_DiscountService_serviceDesc, srv)
}

func _DiscountService_GetDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).GetDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DiscountService/GetDiscount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).GetDiscount(ctx, req.(*GetDiscountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiscountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DiscountService",
	HandlerType: (*DiscountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDiscount",
			Handler:    _DiscountService_GetDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discount.proto",
}
